import { expect, test } from '@playwright/test';

test('administrator: login, employee filtering, policy validation, creation and audit', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/policies/new');
  await expect(page).toHaveURL(/login\?returnUrl/);
  await page.getByRole('button', { name: 'Administrator', exact: true }).click();
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Create policy', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Create policy', exact: true }).click();
  await expect(page.getByText('Select at least one permission.')).toBeVisible();
  await page.getByLabel('Policy name').fill('Quarterly auditor access');
  await page.getByLabel('Description', { exact: false }).fill('Review of financial reports.');
  await page.getByLabel('Role', { exact: false }).selectOption('auditor');
  await page.getByRole('combobox', { name: 'Resource *', exact: true }).selectOption('Financial data');
  await page.getByLabel('Read', { exact: true }).check();
  await page.getByLabel('Access duration').selectOption('scheduled');
  const start = new Date(); start.setDate(start.getDate() + 2);
  const end = new Date(); end.setDate(end.getDate() + 10);
  await page.getByLabel('Start date').fill(start.toISOString().slice(0, 10));
  await page.getByLabel('End date').fill(start.toISOString().slice(0, 10));
  await page.getByLabel('Require MFA').uncheck();
  await page.getByRole('button', { name: 'Create policy', exact: true }).click();
  await expect(page.getByText('The end date must be after the start date.')).toBeVisible();
  await expect(page.getByText('Access that includes production requires MFA.', { exact: true })).toBeVisible();
  await page.getByLabel('End date').fill(end.toISOString().slice(0, 10));
  await page.getByLabel('Require MFA').check();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'test-results/policy-form-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Create policy', exact: true }).click();
  await expect(page).toHaveURL(/\/policies$/);
  await expect(page.getByRole('row').filter({ hasText: 'Quarterly auditor access' })).toContainText('MFA required');
  await page.getByRole('link', { name: 'Audit log' }).click();
  await page.getByRole('textbox', { name: 'Search events' }).fill('Quarterly auditor');
  await expect(page.getByRole('row').filter({ hasText: 'Quarterly auditor access' })).toContainText('Policy created');
  await page.getByRole('link', { name: /Employees/ }).first().click();
  await expect(page.getByRole('link', { name: 'Profile: Anna Kowalska' })).toBeVisible();
  await page.screenshot({ path: 'test-results/employees-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('link', { name: 'Profile: Maria Kozłowska' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Search employees' }).fill('Tomasz');
  await expect(page.getByRole('link', { name: 'Profile: Tomasz Nowakowski' })).toBeVisible();
  await expect(page.getByText('1–1 of 1 results')).toBeVisible();
  await page.getByRole('link', { name: 'Profile: Tomasz Nowakowski' }).click();
  await expect(page.getByRole('heading', { name: 'Tomasz Nowakowski' })).toBeVisible();
  await expect(page.getByText('Baseline employee access', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'All employees' }).click();
  await expect(page.getByRole('link', { name: 'Profile: Anna Kowalska' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Search employees' }).fill('nonexistent');
  await expect(page.getByText('No results', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test('auditor: read-only role, direct route protection and mobile navigation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/login');
  await page.getByRole('button', { name: 'Auditor', exact: true }).click();
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Employees/ })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Profile: Anna Kowalska' })).toBeVisible();
  await page.screenshot({ path: 'test-results/employees-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('link', { name: 'Roles & permissions' }).click();
  await expect(page.getByRole('table', { name: 'System role permissions matrix' })).toBeVisible();
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('link', { name: 'Access policies', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Access policies' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'New policy' })).toHaveCount(0);
  await page.goto('/policies/new');
  await expect(page).toHaveURL(/forbidden$/);
  await expect(page.getByRole('heading', { name: 'This section requires an administrator role' })).toBeVisible();
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page).toHaveURL(/login$/);
  await page.goto('/employees');
  await expect(page).toHaveURL(/login\?returnUrl/);
});
